# Generated by Django 4.0 on 2021-12-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
