# Generated by Django 4.0 on 2021-12-26 04:38

from django.db import migrations
import wallet.managers


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', wallet.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
